User's Guide
------------

This part of the documentation which is mostly prose, being with some
background information about Gateway, then focuses on step-by-step
instructions for gateway development with Gateway.

.. toctree::
    :maxdepth: 2

    installation   
    quickstart
    tutorial
    deploying/index

Additional Notes
----------------

.. toctree::
    :maxdepth: 2

    changelog
    license
